# Generated by Django 5.2.6 on 2025-09-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halalKitchenApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authmodel',
            name='role',
            field=models.CharField(default='user'),
        ),
    ]
