# Generated by Django 5.2.6 on 2025-09-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halalKitchenApp', '0002_authmodel_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authmodel',
            name='username',
        ),
    ]
