# Generated by Django 5.2.6 on 2025-09-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halalKitchenApp', '0003_remove_authmodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='authmodel',
            name='username',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
