# Generated by Django 5.2.6 on 2025-09-15 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halalKitchenApp', '0004_authmodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authmodel',
            name='role',
        ),
    ]
