# Generated by Django 5.2.6 on 2025-09-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halalKitchenApp', '0005_remove_authmodel_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100)),
                ('product_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product_description', models.TextField(blank=True, max_length=200)),
                ('product_image', models.ImageField(blank=True, upload_to='product-images/')),
            ],
        ),
    ]
