# Generated by Django 5.2.6 on 2025-09-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halalKitchenApp', '0008_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authmodel',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
