# Generated by Django 5.2.6 on 2025-10-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halalKitchenApp', '0009_alter_authmodel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt',
            field=models.ImageField(default=1, upload_to='receipts/'),
            preserve_default=False,
        ),
    ]
