# Generated by Django 5.2.6 on 2025-10-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halalKitchenApp', '0011_order_status_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
