# Generated by Django 5.2.7 on 2025-10-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halalKitchenApp', '0012_alter_order_total_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
